version: "3"
services:
  server:
    image: json-rpc-api-proxy-test-server
    build:
      context: ..
      dockerfile: int/server/Dockerfile
    healthcheck:
      test: nc -z 0.0.0.0 3000
      interval: 3s
      retries: 3
      start_period: 1s

  client:
    image: jrpc-client
    build:
      context: ..
      dockerfile: int/client/Dockerfile
    environment:
      SERVER_HOST: server
      SERVER_PORT: 3000
    depends_on:
      server:
        condition: service_healthy
